name: Dual Structure Usage Example

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Example 1: Using the reusable workflow (recommended for consumers)
  build-with-workflow:
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@main
    with:
      version: "v1.0.0"
      iso: true
      summary_artifacts: true
      push_repository: "ghcr.io/example/kairos"
      push_repository_username: ${{ secrets.GITHUB_TOKEN }}
      push_repository_password: ${{ secrets.GITHUB_TOKEN }} 