name: Kubernetes Kairos Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-k3s:
    name: Build K3s Kairos
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@main
    with:
      version: "auto"
      base_image: "ubuntu:24.04"
      model: "generic"
      kubernetes_distro: "k3s"
      kubernetes_version: "v1.28.0"
      iso: true
      raw: true
      security_checks: "grype,trivy"
      sign_artifacts: true
      summary_artifacts: true

  build-k0s:
    name: Build K0s Kairos
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@main
    with:
      version: "auto"
      base_image: "opensuse/leap:15.6"
      model: "generic"
      kubernetes_distro: "k0s"
      kubernetes_version: "v1.28.0"
      iso: true
      security_checks: "grype"
      summary_artifacts: true 