name: Specialized Models Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-rpi:
    name: Build Raspberry Pi
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@main
    with:
      version: "auto"
      base_image: "ubuntu:24.04"
      model: "rpi3"
      arch: "arm64"
      kubernetes_distro: "k3s"
      kubernetes_version: "v1.28.0"
      iso: true
      security_checks: "grype"
      summary_artifacts: true

  build-nvidia:
    name: Build NVIDIA Jetson
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@main
    with:
      version: "auto"
      base_image: "ubuntu:22.04"
      model: "nvidia-jetson-agx-orin"
      arch: "arm64"
      kubernetes_distro: "k3s"
      kubernetes_version: "v1.28.0"
      raw: true
      security_checks: "grype,trivy"
      summary_artifacts: true

  build-trusted-boot:
    name: Build with Trusted Boot
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@main
    with:
      version: "auto"
      base_image: "ubuntu:24.04"
      model: "generic"
      trusted_boot: true
      iso: true
      security_checks: "grype,trivy"
      sign_artifacts: true
      summary_artifacts: true 