name: Workdir Kairos Build Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Kairos image from workdir
        uses: ./
        with:
          workdir: "."  # Explicitly specify the working directory
          version: "auto"
          base_image: "ubuntu:24.04"
          model: "generic"
          arch: "amd64"
          artifacts: "iso"
          summary_artifacts: true 