name: Workdir Kairos Build Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@main
    with:
      workdir: "."  # Explicitly specify the working directory
      version: "auto"
      base_image: "ubuntu:24.04"
      model: "generic"
      arch: "amd64"
      iso: true
      summary_artifacts: true 